### ISSUE TITLE
Preserve ADE telemetry data indefinitely

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/Community#101]
The ADE is currently pruning user metrics after three weeks. Please remove this time limit so that any telemetry data is retained permanently.

**Comment by gchang** [comment]
Behavior may be different on Che 7, need to investigate.

**Comment by gchang** [comment]
This is still valid and open for Che 7.

**Comment by gchang** [comment]
Brian to verify, could be already done.
