### ISSUE TITLE
Report Algorithm Registration Failure if GitLab Pipeline Fails

### ISSUE THREAD

**Issue by NamrataM** [MAAP-Project/Community#143]
Even before the Gitlab build fails, the API sends back a response if the appropriate files were created and pushed to the `register_job` repo. 
We see the following response, but the algorithm registration has actually failed.
`{
    "code": 200,
    "message": "Successfully registered agb_jaxa_demo_metrics-test_ubuntu:jaxa_analysis"
}`

**Comment by NamrataM** [comment]
![MAAP registration acknowledgement.jpg](https://images.zenhubusercontent.com/5eebbe7ef0b8f079c923d734/87d1ce13-4fbd-42dc-8e16-524c75cbd406)

This is the design for the algorithm registration to correctly reflect CI job success / failure.
We need to add a webhook on ADE and a Gitlab Webhook for the API machine.
We would need to add a new table to the MAAP DB on the API machine. It would have the following fields:
- member id
- algorithm_key
- creation_datetime
- commit_hash
- username
- email

**Comment by NamrataM** [comment]
The update response now from the registration endpoint will be:
`{ "code": 200, "message": "Successfully initiated registration of  agb_jaxa_demo_metrics-test_ubuntu:jaxa_analysis" }`

**Comment by bsatoriu** [comment]
@gchang @NamrataM @echyam as part of this new workflow, I think it would be beneficial to include a link to the Gitlab CI build log for the MAAP user. We could store this link as another column in the new MAAP db table ("ci_log_url" perhaps). For example: `https://repo.nasa.maap.xyz/root/register-job/-/jobs/1747`
