### ISSUE TITLE
Initiate login prompt when making an unauthenticated MAAP API calls from ADE

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/Community#167]
When a user logs into the ADE, an API token is generated for making MAAP API calls from within the ADE. When running a MAAP JupyterLab extension outside of the ADE, the user should be required to log in to MAAP before making MAAP API calls. 

We already have a toast notification indicating when a MAAP API call fails due to an un-authenticated request. I propose we enhance this so that the user is prompted to login at the time of making an un-authenticated call. Two key examples:

- DPS-related actions (especially algorithm execution) -- when performing an action in the DPS extensions, spawn a login prompt if the user is not already logged in to MAAP. If the user chooses not to login, limit DPS actions to read-only access.
- maap-py calls to CMR -- if the user is not logged in, throw an exception with instructions on how to login.

**Comment by gchang** [comment]
This ticket is still valid and open.

**Comment by grallewellyn** [comment]
PR completed here: https://github.com/MAAP-Project/user-workspace-management-jupyter-extension/pull/5
I am going to review this ticket by making sure the user can't ever be unauthenticated

**Comment by grallewellyn** [comment]
@bsatoriu How do we verify that a user is authenticated? That [updateKeycloakToken](https://github.com/MAAP-Project/user-workspace-management-jupyter-extension/blob/main/src/getKeycloak.js#L40) in user-workspace-management-jupyter-extension was successful? Is that all?

**Comment by bsatoriu** [comment]
@grallewellyn just being able to log into a workspace confirms a user is logged in. To verify the user can make authenticated MAAP API calls, we can check the existence of a `MAAP_PGT` environment variable.

**Comment by grallewellyn** [comment]
I have not recently had a problem logging into my workspace. I just tested in my 
- normal DIT account
- normal OPS account
- test DIT account (doesn't have ops access)

that MAAP_PGT was an environment variable and I could submit jobs via maap-py in a notebook 
Can you think of anything else we could do to test this ticket? @bsatoriu

**Comment by bsatoriu** [comment]
@grallewellyn I think that covers it!
