### ISSUE TITLE
Create a special readme.txt file in every workspace that describes the contents of the workspace folders

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/Community#197]
At the minimum it should describe the different folders in the workspace as a reminder. It can also contain a change log of the workspace as reference to the user.

**Comment by marjo-luc** [comment]
@rtapella Is this something we can add to maap-docs? What info exactly do we want to provide? Also in the ADE help menu?

**Comment by gchang** [comment]
#209 is a better solution if we're going to have anything in the workspace.
