### ISSUE TITLE
Create Documentation/Notebook for proper use of the ADE

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/Community#209]
- [ ] Incorporate comment from #81

**Comment by marjo-luc** [comment]
Is this still relevant or have the recent documentation efforts addressed this? @rtapella

**Comment by rtapella** [comment]
So far we haven't addressed error/failure analysis

I think it should go into the core technical system reference docs

**Comment by rtapella** [comment]
Is it still incumbent on someone making an algorithm to handle stdout / stderr?

**Comment by marjo-luc** [comment]
#197

**Comment by gchang** [comment]
Just need to update for the latest feature, triage-jobs

**Comment by rtapella** [comment]
https://github.com/MAAP-Project/Community/issues/968
maybe close this and use the referenced doc for the triaged-jobs documentation?
