### ISSUE TITLE
NISAR news blurb

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/Community#239]
I was wondering if you’re planning to update the MAAP news on the MAAP frontpage with some news on NISAR. If you and Kaylin agree, we could state that the official NISAR-simulated products with the proper format and metadata have been generated and distributed via the uavsar website, and some of these can be ingested in the MAAP. I think this would be of interest for the biomass community and MAAP users. What do you think? Here is a possible blurb:
 
“””
The NISAR team has generated new simulated NISAR products starting from L-band airborne Uninhabited Aerial Vehicle Synthetic Aperture Radar (UAVSAR) acquired in Southeastern US that can be added to the MAAP to support biomass algorithm development and testing. This new suite of products is provided with the official HDF format and metadata structure planned to be adopted for NISAR. The dataset has been acquired during the 2019 NASA AM-PM campaign and generated by processing the full-resolution UAVSAR radar data so they conform to the instrument and imaging characteristics of NISAR (e.g., reduced resolution, increased noise, dithering). 
“””
 
Two other important news that we could report are (1) the public distribution of the ISCE3 software with the creation of a workspace and (2) the availability of the CARD4L CEOS Polarimetric PSF that is the reference for ARD GVOC products in MAAP and for which we have already code in ISCE3.

**Comment by marjo-luc** [comment]
@gchang Can we close this?
