### ISSUE TITLE
Add links to user documentation, help requests (link to forums), bug submission reporting in Jupyterlab.

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/Community#302]
Provide quick access to these help systems for end users. The implementation should make these links prominent and not just hidden within a menu.

**Comment by gchang** [comment]
Already finished doc and help links in Jupyter's help menu (via extensions). Need to add bug submission.

**Comment by grallewellyn** [comment]
Should we direct users here for bug submission? https://github.com/MAAP-Project/Community/issues 
cc @rtapella

**Comment by rtapella** [comment]
yep 👍

**Comment by gchang** [comment]
Only missing bug submission, @grallewellyn finalizing.
