### ISSUE TITLE
Create Kubernetes EDSC service for ADE

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/Community#326]
The ADE Ops deployment currently uses and Apache site for hosting EDSC on specified port (usually 30052). This solution requires hosting EDSC on a single node in the k8s cluster, and requires a manual setup process. To address these two points, create a new kubernetes based solution that can be deployed as a post-Che deployment step during ADE installation. This will provide load balancing for EDSC and simplify deployment and maintenance of the ADE.

**Comment by bsatoriu** [comment]
@gchang I deployed the EDSC to Ops on the master node using the legacy method, using the AWS load balancer to route 30052 requests to master.

**Comment by gchang** [comment]
Not really relevant, EDSC within MAAP not heavily used to have to refactor as a k8s container.
