### ISSUE TITLE
Can't share workspace (R workspace)

### ISSUE THREAD

**Issue by lauraduncanson** [MAAP-Project/Community#355]
**Describe the bug**
I made a new workspace, icesat2nb33. I want to share it via typing emails, and can't! The share options seem to vary by workspace type. 
<img width="1330" alt="Screen Shot 2021-06-07 at 4 17 19 PM" src="https://user-images.githubusercontent.com/62670136/121082497-2e4c8080-c7ac-11eb-8a06-b795482922e3.png">

**Comment by gchang** [comment]
This won't be an issue in the GCC ops deployment as you can only add by email addresses. @bsatoriu can help fix this in the pilot ops environment by removing you from an organization, but I see that you have existing workspaces open which will cause problems during that process. You'll need to delete those workspaces for the conversion to work.

**Comment by marjo-luc** [comment]
Closing. Addressed.
