### ISSUE TITLE
Remove any hard-coded algorithm references to "'api.ops.maap-project.org"

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/Community#359]
The maap-py constructor accepts a 'maap_host' argument that can be ignored in the Ops environment, since it defaults to "api.maap-project.org". However, since we're running in "*.ops.maap-project.org" during the F2F demos, any algorithms will need to hard-code the host:

```python
from maap.maap import MAAP
maap = MAAP('api.ops.maap-project.org')
```

Once F2F is over and we are fully migrated to GCC, put together a list of any references to the old *.ops.maap-project.org urls so they can be removed.

**Comment by gchang** [comment]
@bsatoriu Is this done? Seems like it should be.

**Comment by bsatoriu** [comment]
@gchang this was meant to serve as a reminder to update the references within the algorithms. This is one example: https://repo.ops.maap-project.org/lduncanson/icesat2_boreal_dps/-/blob/master/2.3/2.3_DPS.ipynb

**Comment by gchang** [comment]
Waiting for pilot ops migration to gcc
