### ISSUE TITLE
DPS Jobs UI Redesign (Revision 1) and Implementation

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/Community#365]

**Comment by marjo-luc** [comment]
Adding link to the figma wireframe for easy access:
https://www.figma.com/file/5NUR3wM09Hbf7hvsM6jgft/jobs-ui?node-id=228%3A1727

**Comment by anilnatha** [comment]
@marjo-luc Based on the comments I've added to the figma board, I can create tickets for each of the proposed changes we agree on that are needed for the meeting on the 19th with the UWG.

**Comment by marjo-luc** [comment]
Discussion with @anilnatha and @sujen1412 regarding UWG feedback meeting on 7/19/21:

1. Rework jobs ui to separate 'Submit Jobs' from 'View Jobs'. 'Submit Jobs' would be a modal that has the existing functionality, but also include an option to copy the generated code to the clipboard for users to paste into jupyter notebooks. 'View Jobs' would be a main area widget and would be reworked to leverage the react-table module which offers easy-to-use column filtering options.

2. Implementation of the extensive filters available from react-table will allow users to easily filter down to only jobs of interest, reducing the risk of being overwhelmed by potentially thousands of job records. We would also train users to use user-tags to make it easier to view batch jobs.

3. Do we want to remove the 'Delete' and 'Dismiss' functionality from the jobs ui? No longer permitting these would allow us to keep better provenance. 

4. Investigate how to display job inputs and full traceback to users and provide more info in general without duplicating Figaro.

**Comment by sujen1412** [comment]
We need to implement a "Stop" Job functionality that would capture the state of the user jobs at the time. 

This job would be a wrapper job that would store the current number of running vs queued jobs and display that to the user in the "view jobs" interface.

Displaying this "stop job" would inform the user of the action they just performed (stop action) and the details captured would (running vs queued) would give the user insights on the state of the system when "stop" was executed.

**Comment by rtapella** [comment]
will add Stop to v2 epic
