### ISSUE TITLE
Change the default API in maap-py

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/Community#367]
**Is your feature request related to a problem? Please describe.**
The current focus is on moving users to GCC, however the *.ops.maap-project.org is going to stick around until Nov as decided to support users. It would be great if this particular change was invisible to users in the ADE, such that code does not need to be changed when API urls change.

Example, current users in GCC have to specify the ops api endpoint.
```
from maap.maap import MAAP
maap = MAAP(maap_host='api.ops.maap-project.org')
```

**Describe the solution you'd like**
Users should not have to know this, and always be able to do:
```
from maap.maap import MAAP
maap = MAAP()
```

**Describe alternatives you've considered**
- Telling users which hostname to use when
- Autodetecting the api url from the workspace ENV
- Changing the default in maap-py to api.ops (would potentially need to be changed back later and/or just ALIAS the domain)
    - Tag the current branch of maap-py in Pilot ops, and modify Pilot Ops images to build with that tag. Then changing the default won't break anything

**Additional context**
This came up while work on automated test of service using the existing [docs](https://docs.maap-project.org).
Should probably be resolved before onboarding more members in the next couple of weeks. 

cc: @abarciauskas-bgse @gchang

**Comment by bsatoriu** [comment]
Auto-detection is feasible. It would require looking for both a Che variable like  `CHE_API_EXTERNAL`, as well as a DPS env variable, which we would need to integrate into the DPS wrapper. This would alleviate a pain point for users and also make algorithms more portable between environments.

**Comment by marjo-luc** [comment]
Implemented.

**Comment by grallewellyn** [comment]
Appears to work in DIT and OPS without having maap_host
Do we want to move this back into open to remove maap_host from automatically being added to the constructor when you click the MAAP icon? The change would be in the maap-libs-jupyter-extension
