### ISSUE TITLE
Reproducibility in Pilot Ops

### ISSUE THREAD

**Issue by gllewellyn19** [MAAP-Project/Community#368]
In order to test the reproducibility in Pilot ops, I created 2 workspaces, git cloned https://github.com/MAAP-Project/maap-jupyter-ide  and then ran the exact same commands in the top level readme and the ipycmc readme. In the past, I believe I had npm run build (my most problematic command when doing local development) running in one Pilot ops workspace and not working in another, but I was unable to demo that again. However, when running the command jupyter labextension install @jupyter-widgets/jupyterlab-manager@2.0 in one controlled workspace, this failed. I then changed the command to jupyter labextension install --minimize=False @jupyter-widgets/jupyterlab-manager@2.0 and it ran, shown here: ![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/6428dbf0-d2c4-45a6-a99f-74821d79c38a). When I ran the previous command in the second controlled Pilot ops workspace, it passed without the minimize tag as shown here: ![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/1164ff29-6b8b-4461-8caa-469c4b15256c). This post is to show that workspaces that are exactly the same in Pilot ops (same RAM too) sometimes have different outcomes when running the same command. This post is to also show how to fix the above error when running jupyter labextension install @jupyter-widgets/jupyterlab-manager@2.0. Also, the maap-jupyter-ide readme could be modified to suggest this fix in its Troubleshooting section.

**Comment by marjo-luc** [comment]
No longer relevant.
