### ISSUE TITLE
Link in header on search page cannot load

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/Community#383]
When the "EarthData" logo is clicked, the browser is unable to load the link because this area of the page is loaded inside of an iframe.

![Screen Shot 2021-07-13 at 10.49.24.png](https://images.zenhubusercontent.com/5d33ee8c39dd735797c45637/0436e67c-3aa9-49fe-b043-b095eef7044b)

![Screen Shot 2021-07-13 at 10.50.05.png](https://images.zenhubusercontent.com/5d33ee8c39dd735797c45637/ad254344-0246-4feb-85d8-9c2f69f60b41)

Remedies to consider:

1. Add a `target` attribute to the anchor tag with a value of "_top" (preferred) or "_blank".
2. Remove the nested EathData Header as it not only introduces this issue, visually it is confusing to have multiple header rows.

**Comment by anilnatha** [comment]
This issue may be a moot if we remove the "Explore" -> "Search Catalog" link in the portal as this page is currently broken.

Need clarification on #924 from @gchang before we make a decision on what to do with this ticket.

**Comment by gchang** [comment]
Commented on #924

**Comment by anilnatha** [comment]
Searching Earth Data from the portal is [no longer supported](https://github.com/MAAP-Project/Community/issues/924) so this ticket is moot.
