### ISSUE TITLE
DPS-CMR Interaction

### ISSUE THREAD

**Issue by NamrataM** [MAAP-Project/Community#387]
We need a procedure for delivering products to CMR. Currently the only way to do so is follow [steps](https://docs.google.com/document/d/15IMZ7yEom7wtXK8KeAg7coIToXqOTAoWjwk5XJUxobo/edit) to share data via the notebooks. And in order to create or update a CMR collection, users need to go to https://questionnaire.maap-project.org/

**Comment by NamrataM** [comment]
So far the design/implementation ideas are captured[ here](https://paper.dropbox.com/doc/Meeting-notes-DPS-CMR-Interaction--BOeOnC9nPA7w1xs2hrIldNsdAQ-use9kgnKvY8QVgvCVM9AS). 


Scenarios of CMR Delivery:
1.  Collection exists, and user wants to deliver generated product
2. Collection exists, and user wants to run algorithm and push it’s output to CMR
3. Collection doesn’t exist, and user wants to deliver generated product

NOTE: Users must select an existing collection if they want to run algorithm and push it’s output to CMR automatically. If the collection they are interested in doesn’t exist, they need to follow scenario 3.

New DPS Delivery Job to be implemented:
This is going to be an internal DPS job. 
- It will be either triggered by a successful algorithm run when the user wants the products published to CMR
- It will be run when the user decides that they want to publish products they generated in previous algorithm runs.

**Comment by NamrataM** [comment]
Started new [repo](https://repo.nasa.maap.xyz/maap-devs/publis-product-to-cmr) for DPS job for delivering products to CMR.

**Comment by NamrataM** [comment]
Moved [repo](https://github.com/MAAP-Project/publish-products-to-cmr/tree/imgspec-inherit) to Github.

**Comment by NamrataM** [comment]
From meeting with Aimee on 08/02 -

Workflow is:

1. create a cumulus collection in cumulus (in the user-metadata-form)
2. create a collection draft as a draft CMR collection to the metadata management tool (MMT) (in the user-metadata-form)
3. (Human) Reviews draft collection and publishes it to CMR. Once collection draft is approved, trigger DPS job publishToCmr. Also associate Cumulus Collection with DPS JobId. Collection is published to CMR from the MMT application. (human + mmt)
4. DPS job publishToCmr creates the Cumulus rule which kicks off "discover and queue" which discovers all the granules and "ingests" them which includes publishing the granule metadata to CMR (mmt)

Work to do:

- discover and queue will need to look up the granules using the job id and DPS API
- perhaps the cumulus collection should also be created in step 3 so one of the systems doesn't have to "update" the existing cumulus collection
- notify the user when the collection draft is accepted or rejected
- notify the user when ingest fails

**Comment by NamrataM** [comment]
From meeting with Aimee and Phil on 09/21:
Discussed interface and workflow.

JPL Progress:
CMR Delivery job ready to build and test. Waiting for Endpoint and provider information

JPL To Do:
-Check if all DPS buckets are in us-west-2 @Namrata M 
- Check network access on worker to run DPS Delivery job @Namrata M 

DevSeed To Do:
- Create a "DPS Test" collection in CMR
- Need a DPS bucket provider for each environment created in cumulus, with S3 protocol, multiple environments
- Need to determine the endpoint for creating Cumulus collections and rules from the Cumulus stack (maap-prod-uw2), configure with DNS
- hand cumulus endpoint to DPS/ADE team so they can post / put to collections and post to rules
- We can also this workflow with collection information provided JPL team
- test collection provided by MAAP JPL team can work for kicking off an ingest
- Contract: short name that gets created as the CMR collection's short name needs to also be the name of the cumulus collection

**Comment by gchang** [comment]
By end of 2021, be able to run a simple test in DIT.

**Comment by sujen1412** [comment]
Not high priority and will be replaced by stac.
