### ISSUE TITLE
Potentially need to change nodejs version for maap-jupyter-ide readme

### ISSUE THREAD

**Issue by gllewellyn19** [MAAP-Project/Community#396]
I started getting seg faults in previous conda environments when trying to run commands that start with npm (even though it was working yesterday). I also could no longer run the readme commands when creating a new conda environment as shown below.
![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/9c73973c-a284-4afd-9729-817c5fbeecc5)
![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/cb3ec48c-abdc-41e6-8508-74c7771aa2aa)
![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/de257d79-ae98-46f5-bf89-e04076ee3d84)
![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/6cdbafb9-f12d-41b3-bc88-61582da4f5fa)

After much debugging, I think the problem is the version of nodejs in the command `conda install conda=4.7.12 jupyterlab=2.1.4 nodejs=10.13.0 gitpython=3.0.2` since nodejs installs npm. I changed this line to `conda install conda=4.7.12 jupyterlab=2.1.4 nodejs=16.5.0 gitpython=3.0.2` and now all the top level readme commands work for me again. I know that there certainly may be other problems that this created, but it may be worth considering changing the version of nodejs.

However, running the readme commands for ipycmc, currently, `npm install` is failing and I think that it might have to do with this message: 
![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/489f489c-bcc8-483a-a3c1-f2d365583401)
This is the log file that I am getting:
![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/93403c6b-15a3-410e-a69c-d74cf4f19b0c)
I think that the error might be from node-sass because of this, but there is no node-sass in the package.json file for ipycmc (although another package might be installing it). I tried doing `npm install node-sass` then `npm install` again and I get the same error message. 

The readme commands for edsc_extension run fine (one of those commands is `npm install`). 

I also created a new conda environment with all the readme commands this morning in Ops and it worked fine. Therefore, I am not sure if this is a "me" problem or a problem that could potentially affect other people. But the fact that I created a brand new conda environment and encountered these issues leads me to believe other people might have this problem.

**Comment by gllewellyn19** [comment]
Update: the top level and ipycmc readme commands worked fine in gcc ops environment so this might just be a WSL problem

**Comment by marjo-luc** [comment]
@grallewellyn Given that the maap-jupyter-ide repo is no longer used, is this ticket still relevant?

**Comment by grallewellyn** [comment]
@marjo-luc No, I don't believe it is still relevant
