### ISSUE TITLE
maap-jupyter-ide "user_meta_form" TEMPORARILY DISABLED 

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/Community#441]
The maap-jupyter-ide GitLab CI [recently began failing due to typescript errors](https://mas.maap-project.org/root/jupyter-image/-/jobs/2752) in the user_meta_form plugin (lines 1555-1566). If this plugin still supported? If not, I propose we remove it from the repo. If it is still in use, the Typescript error needs to be fixed. 

Until this error is resolved, I have temporarily removed it from the build: https://mas.maap-project.org/root/jupyter-image/-/blob/master/docker/Dockerfile#L131

**Comment by marjo-luc** [comment]
@bsatoriu Given that the maap-jupyter-ide repo is no longer used, is this ticket still relevant? The user-metadata-form was converted into its own extension and is deployed on ops.

**Comment by grallewellyn** [comment]
I agree with @marjo-luc that this ticket no longer seems relevant

**Comment by rtapella** [comment]
and it just links to the Github page to make a request now?
if so yes we can close this out

**Comment by marjo-luc** [comment]
I fixed the typescript issue when we converted all of the extensions from the maap-jupyter-ide repo into their own npm packages. The extension just redirects users to the metadata questionnaire, which I believe is maintained by the data team.
