### ISSUE TITLE
Running resource-intensive notebook in ADE causes Jupyterlab errors

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/Community#452]
Reported by David Minor:

Running the cells of [this Biomass Harmonization notebook](https://repo.ops.maap-project.org/lduncanson/biomass_harmonization/-/blob/5dd0efff981f375599c80e407105a8a3021d9256/forest_biomass_summary-SoAm-demo.ipynb) causes the notebook to become corrupted and unusable. 

> Any time I try to open the notebook, the "Close without saving?" dialogue box pops up. If I click "OK", the notebook closes, if I click "Cancel" the notebook has a spinning wheel but does not load.

We worked around the error by replacing the notebook from the Gitlab version:

```shell
(base) root@workspaceujs7e7l6csdixtz0:~/git/biomass_harmonization# rm forestcover-SoAm-demo.ipynb 
(base) root@workspaceujs7e7l6csdixtz0:~/git/biomass_harmonization# wget https://repo.ops.maap-project.org/lduncanson/biomass_harmonization/-/raw/master/forest_biomass_summary-SoAm-demo.ipynb
```

As a long term solution, investigate the full set of side effects from executing tasks in the ADE that exceed the workspace's CPU limit. In addition to the notebook corruption, I noticed Che spawned three evicted pods for David's workspace. If feasible, handle these failures more gracefully by informing users of the nature of the notebook error.

**Comment by bsatoriu** [comment]
David provided this sample code snippet that triggered his Jupyter lab error:

```python
extent(cci_overlap) <- overlap_extent
extent(gfc_thresholded_overlap) <- overlap_extent
cci_resample <- resample(cci_overlap, gfc_thresholded_overlap, method="bilinear")
```

Note: `cci_overlap` and `gfc_thresholded_overlap` are both raster objects.

David also added that he's not able to reliably produce the error with this code, so we may not be able to take action on this issue if unable to reproduce.

**Comment by marjo-luc** [comment]
Resolved. Closing.
