### ISSUE TITLE
Direct download of protected Earthdata Cloud URLs in maap-py

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/Community#515]
Given a URL that is protected by EDL, allow the direct download of that url without having to perform a CMR search (via maap.searchGranule) first.

**Comment by bsatoriu** [comment]
### Testing notes

The following python script should trigger a download of an ASF granule to a local `tmp` directory when run within the ADE. 

```
result = maap.downloadGranule(
  online_access_url='https://datapool.asf.alaska.edu/GRD_HD/SA/S1A_S3_GRDH_1SDH_20140615T034444_20140615T034512_001055_00107C_8977.zip',
  destination_path='./tmp'
)

print(result)
```

For more info see: https://github.com/MAAP-Project/maap-py/blob/develop/maap/maap.py#L127

**Comment by oddes** [comment]
@bsatoriu works as expected in UAT. See the download here:
<img width="1788" alt="Screenshot 2023-11-02 at 4 44 05 PM" src="https://github.com/MAAP-Project/Community/assets/34038615/d2622d3c-fa70-47b4-8b72-9cd6155ded1b">
