### ISSUE TITLE
Register Algorithm from ADE is not working as expected.

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/Community#521]
Steps:

1. Clone the repo  and open ADE:
https://github.com/MAAP-Project/dps-unit-test.git
2. Now right select the yaml file and select "Register as MAS Algorithm" you will notice it will take long time to open a window create an algorithm. 
3. Now try to list the algorithm you will notice it wont appear.

**Comment by sujen1412** [comment]
Closing this as a non issue in the new release.
