### ISSUE TITLE
Upgrade PostgreSQL

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/Community#542]
@bsatoriu 

Just learned that PostgreSQL 10 will no longer be updated after November 10 of this year so we will need to upgrade our environments that are running this version prior to that.

> PostgreSQL 10 EOL Notice
> PostgreSQL 10 will stop receiving fixes on November 10, 2022. If you are running PostgreSQL 10 in a production environment, we suggest that you make plans to upgrade to a newer, supported version of PostgreSQL. Please see our [versioning policy](https://www.postgresql.org/support/versioning/) for more information.

Reference: https://www.postgresql.org/about/news/postgresql-143-137-1211-1116-and-1021-released-2449/

**Comment by bsatoriu** [comment]
Thanks, @anilnatha. Sounds like a plan.

**Comment by anilnatha** [comment]
November snuck up on us @bsatoriu !

PostgreSQL 10 is now past its support period.
