### ISSUE TITLE
Create a function to get a pre-signed-link for files on s3 is maap-py 

### ISSUE THREAD

**Issue by sujen1412** [MAAP-Project/Community#565]
Could include something like this in maap-py

`
import logging
import boto3
from botocore.exceptions import ClientError

def create_presigned_url(bucket_name, object_name, expiration=3600):
    """Generate a presigned URL to share an S3 object

    :param bucket_name: string
    :param object_name: string
    :param expiration: Time in seconds for the presigned URL to remain valid
    :return: Presigned URL as string. If error, returns None.
    """

    # Generate a presigned URL for the S3 object
    s3_client = boto3.client('s3')
    try:
        response = s3_client.generate_presigned_url('get_object',
                                                    Params={'Bucket': bucket_name,
                                                            'Key': object_name},
                                                    ExpiresIn=expiration)
    except ClientError as e:
        logging.error(e)
        return None

    # The response contains the presigned URL
    return response
`

And then users can use it 

`
maap.create_presigned_url()
`

**Comment by gchang** [comment]
Isn't this already done with an API call that can already be done in jupyter workspaces?

**Comment by gchang** [comment]
Haven't heard a need for this in the past year.
