### ISSUE TITLE
Accessing ADE after changing URS password seems to fail

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/Community#566]
A EIS user had recently changed his password and tried logging in. Eclipse Che then responded with  'An error occurred, please login again through your application'

**Comment by oddes** [comment]
@gchang @bsatoriu  
Unable to re produce the issue: here are the steps I have followed:
1. Updated my URS password.
2. Logged in to the (https://ops.maap-project.org/) with the updated password.
3. I have logged in to the ADE with no issues.
