### ISSUE TITLE
Jobs UI: sort arrows point in the wrong direction and are always showing for time field

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/Community#612]
The column sort-indicators in the Jobs UI have arrows that point the "wrong way". Also for the date fields, the sort-indicators are always showing so you cannot easily tell which is active.

![Screen Shot 2022-11-11 at 3.12.39 PM.png](https://images.zenhubusercontent.com/61dc908470b3029fc627fcbb/5f379b61-a18d-429e-b09b-8915afdec138)

**Comment by marjo-luc** [comment]
Fixed with #649
