### ISSUE TITLE
Jobs UI: after successfully submitting job, auto-refresh the job listing 

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/Community#613]
After successfully submitting a job, auto-refresh the job listing so that you can flip to it and see your running job. Currently when you flip to job status you must manually Refresh the listing to see the job(s) you just submitted, so it looks like they are not there.

**Comment by rtapella** [comment]
We could also let ppl click the notification/toast and go to the View page and highlight the row for their job

**Comment by marjo-luc** [comment]
This has been implemented; however, testing showed the refresh often completes before the job is processed by the DPS, so users may need to manually refresh to see the job they've just submitted.

Changes available in this image:
mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/vanilla:version-updates

**Comment by rtapella** [comment]
Yeah I noticed the timing as well. Can the refresh happen after a small delay?

**Comment by rtapella** [comment]
Also when you "Submit Job" there is no feedback that your job was submitted on the submit page. 

e.g. disable the submit button and show a notification that the job was submitted

**Comment by marjo-luc** [comment]
I can add a delay in the refresh.

A toast should pop up in the bottom right corner of the workspace upon job submission, with the status of the job submission. This happens locally, but I no longer see this on my DIT workspace. I'll look into it.

**Comment by rtapella** [comment]
I don't know what triggers the refresh but... perhaps:

1. click Submit
2. Submit is disabled for ~1 second with a "spinner" mouseover thing suggesting that something is happening
3. Notification toast happens
4. Refresh of View is triggered & Submit is enabled again

**Comment by rtapella** [comment]
Is the Toast triggered by a "good" response from WPS?

**Comment by marjo-luc** [comment]
A toast will pop up for any response upon job submission. If good, it tells the user the job was submitted successfully and contains the job_id; if bad, it tells the user the job failed to submit.
