### ISSUE TITLE
Jobs UI: from "Product" field of metadata, link to a path in Terminal

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/Community#614]
It might be interesting to let people click a link in the Products field to open a new Terminal and go to the path of an output file.

Or potentially just let them copy/paste the link and it's more flexible (it's hard to copy/paste links sometimes). Need to observe how people will use the output-path info.

You could have little action-icons for each path:
- go to path in Terminal
- copy path
- copy some sort of Python code snippet? Maybe just copy path is effectively the same as this and more flexible (e.g. for R etc.)
- open up an image directly? e.g. jpg/png/tiff?

**Comment by grallewellyn** [comment]
Duplicate ticket to #656
