### ISSUE TITLE
Interactive tutorial for MAAP workspace

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/Community#618]

**Comment by grallewellyn** [comment]
New jupyter extension with an interactive tutorial for MAAP specific features. Thinking about using joyride, but need to explore more

**Comment by gchang** [comment]
- [ ] Wait until the new UI changes are made to finalize configuration
- [ ] Create documentation on how to create tutorials

**Comment by grallewellyn** [comment]
Note that we also want to create the capability:
1. If a user has workspace 1 created with version v1 of Basic Stable
2. And they create a new workspace from basic stable with version v2 of basic stable, a notification will appear for them with a link to a changelog (we still need to create the changelog)

**Comment by gchang** [comment]
Push out as 1.0.0 once the tutorial for the memory status item is updated.

**Comment by grallewellyn** [comment]
Separate menu item called "MAAP Help" Should no longer be included in general help menu

**Comment by rtapella** [comment]
I... actually don't really agree with this. I think it should stay in the main Help menu.

**Comment by grallewellyn** [comment]
I agree with @sujen1412 's point a user might not think to look in the help menu 

ie in the case they forgot that the tour says the tour can be accessed in the help menu or they say don't show the tour again and there is a notification that the tour can be accessed in the help menu, but both these things could only happen once at the beginning and months later the user might not remember it

**Comment by rtapella** [comment]
I do not think that making two Help menus is the right solution. Is there another application you use with multiple help menus? That might help me understand the need.

I am wary of making assumptions of our science users based on the development team's mental models.  I think we should also test our assumptions before starting to multiply our menus again.

**Comment by grallewellyn** [comment]
Yes, 2 help menus could be confusing

Maybe we can discuss next week when we go over these tickets
