### ISSUE TITLE
Stop jobs

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/Community#640]
Sujen: 

We need to implement a "Stop" Job functionality that would capture the state of the user jobs at the time.

This job would be a wrapper job that would store the current number of running vs queued jobs and display that to the user in the "view jobs" interface.

Displaying this "stop job" would inform the user of the action they just performed (stop action) and the details captured would (running vs queued) would give the user insights on the state of the system when "stop" was executed.

**Comment by rtapella** [comment]
from Jobs UI Usability Test & previous feedback

**Comment by rtapella** [comment]
Another factor:
jobs can get stuck in Pending state. These need to be stopped and re-tried.

**Comment by sujen1412** [comment]
First draft, we will expose a maap-py function to "cancel" a single job by id. 
```
maap.cancelJob("id")
```

We choose to go with the word `cancel` instead of `stop` to cover both cases of job statuses i.e. queued or started. 
Jobs that have completed cannot be cancelled.

**Comment by oddes** [comment]
Works as expected
