### ISSUE TITLE
Sort/filter on each column of the Jobs UI

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/Community#649]
Jobs UI Usability testing

Each column of the jobs UI should allow filtering and sorting.

Also the bug where several columns look like they are being actively sorted should be fixed
![Screenshot 2023-01-11 at 12.04.18 PM.png](https://images.zenhubusercontent.com/61dc908470b3029fc627fcbb/066180ff-c952-47d8-98b3-cb6b88e1adbb)

**Comment by rtapella** [comment]
For columns with a controlled vocab (e.g., status), the filter should be a Dropdown menu with all available options showing (and existing/valid options active; if a particular option is not valid then make it inactive in the Dropdown menu)

**Comment by rtapella** [comment]
for date columns, add a text input box as filter

**Comment by rtapella** [comment]
for date columns, add a date-range picker that allows a single date

**Comment by oddes** [comment]
<img width="1186" alt="Screenshot 2023-11-02 at 5 16 42 PM" src="https://github.com/MAAP-Project/Community/assets/34038615/4ee229ac-7bfd-4749-be6a-3e63f758fa14">
