### ISSUE TITLE
jobs UI: expose the entire stderr

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/Community#651]
jobs ui usabilty test:

"would be nice to expose the entire stderr if possible"

**Comment by marjo-luc** [comment]
This is what it looks like in the UI -- default is collapsed view; user clicks to expand entire traceback:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1l2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22354651a6991e5571976327bc834d2fd647ed4c/collapsed.png)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2N2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae2d10fc5d9b05f9dc60f68342139626fa5b2857/expanded.png)

**Comment by rtapella** [comment]
Is there an easy way to add an indication that it’s an expandable element? E.g. disclosure triangle or “expand” button

**Comment by oddes** [comment]
works as expected.
