### ISSUE TITLE
Jobs UI: Prevent rapid "double-submit" errors

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/Community#663]
- there's a notification when you submit a job, which is good
- you can easily submit the same job twice by pushing the Submit button twice
- if you're running a large job (or a batch) this could cause you to "spend a lot of money" by accident

- prevent the same job from being submitted twice within some time period, e.g. within 5 seconds. This will prevent accidentally double-press errors that trigger the same thing rapidly in succession by accident

**Comment by grallewellyn** [comment]
Or once the user presses the submit job button, we could disable the submit job button until the job has been successfully submitted? Because I think this problem is arising from the fact that there is a delay between clicking the submit job button to the notification for job being submitted

**Comment by rtapella** [comment]
Yep that's a good solution.

**Comment by grallewellyn** [comment]
Discussed in spring planning 10/26
We want to still keep button disabling (I basically have this working), but we want a way for the user to be able to tell that it was submitted if they blinked when the button was disabled and missed the toast notification because large monitor. Potential solutions to this
- submit button changes to resubmit if they already submitted. Downside to this is that you have to keep track of changes in the state of what is in the Submit Algorithm Form
- A little text below the submit button saying that the job was submitted and giving the job ID. How long should this stay up?

**Comment by rtapella** [comment]
I think a permanent message below the submit button would be fine. It can be the same content as the notification toast. 

Like
1.
Submitting job...

2a. Change the content to:
October 23 at 13:45 PST
Job submitted successfully with ID blah-blah-blah-blah

(That will link to the View tab and ideally highlight the job you just submitted)

2b. If failed, change content to:
Job submission failed:
[error message]



If another job is run with the same form, wipe the content of this div and go to 1 (submitting job....)

**Comment by grallewellyn** [comment]
Sounds good to me

**Comment by rtapella** [comment]
Jobs submit very quickly. Can we add a minimum disable-time to this? Maybe the "submitting job" can be at least 2 seconds long, and more if the submission is taking a while for some reason.

**Comment by grallewellyn** [comment]
We could and that wouldn't be a difficult change, but then wouldn't that make our system seem slow if we are purposely delaying things and the job had actually submitted? Is the popup notification and the text underneath not enough feedback for the user for them to know their job was submitted and they shouldn't try to submit it again? 
<img width="942" alt="Screenshot 2024-01-18 at 2 06 34 PM" src="https://github.com/MAAP-Project/Community/assets/114033465/99950104-b95c-4a8e-bd6d-0fc93433cf97">

**Comment by rtapella** [comment]
Sometimes it’s good to delay things to help someone understand what’s happening. In this case there’s no reason to click submit repeatedly, and changing an input to submit a similar job a few times is going to take more than 2 seconds. I don’t think it’ll make the system feel slower in any way that matters here. 

I noticed that the “submitting” message flipped by so quickly that I didn’t have time to read it. And I was still able to just keep clicking submit quickly to make a bunch of cloned jobs. So my “concern” is that it won’t be enough to prevent the mistake. 

We could just leave it and test it, as well.

**Comment by grallewellyn** [comment]
Yes, that is a good point 
@marjo-luc What do you think? Should we make this change and move back into in progress?

**Comment by marjo-luc** [comment]
Can we treat this as UX feedback and make the update in the next dev cycle? I'd like to avoid non-critical dev changes the evening before a release to production.

**Comment by grallewellyn** [comment]
I agree, I didn't mean for this release, I meant for the next release

**Comment by rtapella** [comment]
👍

**Comment by marjo-luc** [comment]
@grallewellyn Let's create a new ticket and reference this one in it.
