### ISSUE TITLE
Jobs UI: table-view needs some sort of affordance to indicate that you click a row to show the Details Panel

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/Community#666]
some affordances we could try:
- mouseover color
- mouseover icon shows up

**Comment by marjo-luc** [comment]
Like this? Light blue is selected row and grey is hovered row. I pulled this from DIT.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0VhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25512e421900e3837b8974f5381dc769a15aab2c/Screenshot%202023-10-09%20at%204.29.24%20PM.png)

**Comment by rtapella** [comment]
👍

**Comment by marjo-luc** [comment]
Closing this ticket out as it's been implemented.
