### ISSUE TITLE
Notification space 

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/Community#681]

**Comment by grallewellyn** [comment]
Working on creating a notification space for the ADE so that the user can see/ manage notifications after they appear

**Comment by grallewellyn** [comment]
If I cannot get jupyterlab-notifications to work, I created the following 3 approaches (and did some testing that they would work)
1. Use INotification just like how we are using it now. However, the jupyterlab-toastify package doesn't contain any accessors to see posted INotifications, so everytime we want to post an INotification, we can post it to an API endpoint as an object, like jupyterlab-notifications does (except we will make ours actually work). 
Pros:
- Can continue using INotification
- Don't need to overwrite any packages besides fixing jupyterlab-notifications
Cons:
- Have to create an API endpoint that we can post notifications to 
- Have to post to the API endpoint everytime we want to send a notification in addition to doing INotification.info
- Will need to add API calls to the existing jupyter extensions
- Potentially need to modify the jupyterlab-notifications package if that is what it takes to get it to work


2. I can modify the jupyterlab-toastify package (package that creates INotifications) so that it uses the react-toastify onChange function which is called each time a new notification is added, or we can make an accessor for the list of all INotifications. I then need to modify the jupyterlab-notifications package so it works with this list of notifications (as opposed to using API endpoint which it currently does)
Pros:
- We can continue doing INotificaitions the same way
- Don't need to change the code in the existing jupyter extensions 
Cons:
- Will need to change the imports for the existing jupyter extensions 
- Need to modify the jupyterlab-toastify package
- Need to modify the jupyterlab-notifications package

3. We can use the react-toastify package instead of the jupyterlab-toastify package. Note that under the hood, the jupyterlab-toastify package was already using the react-toastify package. We can use the onChange function for toast to see each time a new notification is added so we add all the notifications to store. Then, we can display them by modifying the jupyterlab-notifications package
Pros:
- Only modifying the jupyterlab-notifications package 
Cons:
- Need to change from INotifications to toast notifications which means changing the code of existing jupyter extensions 
- Need to modify the jupyterlab-notifications package

**Comment by grallewellyn** [comment]
Notification space needs to also solve issue that long job ids cover the x of the INotification

**Comment by grallewellyn** [comment]
No, this would be a plugin (although we might have to change the way to post notifications in the jupyterlab extensions). Those errors would still need to be removed in whatever statement in the code is causing them, which would be outside the scope of the notification space
When I am creating the notification space, I can find the statement that is causing these messages and bring it up to the team for further review

**Comment by grallewellyn** [comment]
@gchang I don't believe there is a need for me to create a notification space anymore because JupyterLab 3.6.x [comes with notifications now](https://jupyterlab.readthedocs.io/en/stable/extension/ui_helpers.html#notifications). This also includes a notification space:
![Screenshot 2023-04-24 at 10.02.06 AM.png](https://images.zenhubusercontent.com/6333605b521a1e34fb21fe22/19c4201d-b285-41a9-ac4f-7ca76aa7806a)

One slight disadvantage to this approach is that [this issue](https://app.zenhub.com/workspaces/maap-platform-5ee7f0d1f440de0024cd359b/issues/gh/maap-project/zenhub/672) is still occurring. And you cannot clear it from the notification space ![Screenshot 2023-04-24 at 10.27.54 AM.png](https://images.zenhubusercontent.com/6333605b521a1e34fb21fe22/9db02d93-2278-467a-8bc6-a341c6642ef6). I don't think it is worth creating an entire notification space just for this issue, so we can either avoid putting long JobIds in the notifications or format the JobId beforehand. There is a way to add a dismiss button to the notification, but you have to add 4 buttons to get the dismiss button to actually show up because the formatting is so weird. 
One thing to note is that sorting isn't automatically done for the notifications (ie into errors vs warnings), but it honestly might be better to just have the notifications sorted by the time they occurred. 
Another thing to note is that if we want the notification to actually show up in the corner (and not just be added to the notification space without a popup), we need to set the autoClose tag for the notification (ie `Notification.error("test one error", {autoClose: 3000});` This is nice because it forces us to question if the user really needs to see that notification, or just have it present in the notification space. We can also just set autoClose to false, but I think we should only do this in (if any) extreme cases. If we are worried the user won't see the notification in the bottom right corner, I can add that to the maap help tour. 

Also, with this approach I will need to do the following to all the jupyter extensions
- Make sure @jupyterlab/apputils is installed in the package.json
- change the imports of jupyterlab_toastify to `import { Notification } from "@jupyterlab/apputils";`
- change the notification calls to `Notification.` instead of `INotification.`
- add the autoClose tag to Notifications that we want to appear on the screen (not just appear in the notification space)

Also, to address @rtapella 's concerns, there is a clear all button and you can clear individual notifications. And I can find where the "Get user jobs failed" and "User's SSH Key undefined" errors are occurring and either delete them, or have them just go in the notification space without appearing on the screen first

**Comment by rtapella** [comment]
Maybe we should only have the "red errors" show up as popups and have the other informational/warning ones only be in the notification space (without a popup).

**Comment by rtapella** [comment]
Also I 100% agree that we should not replace the Jupyter notifications so that we don't need to manage that bit and do integration testing with it etc.

**Comment by gchang** [comment]
@grallewellyn Is the long text error something you can fix with CSS, specifically the [overflow property](https://www.w3schools.com/css/css_overflow.asp) (overflow: scroll?)? Try manually injecting that overflow property via your browser's developer tool and see if it fixes it. If so, maybe it's something you can fix and contribute back to the community.

**Comment by grallewellyn** [comment]
![Screenshot 2023-04-25 at 12.46.05 PM.png](https://images.zenhubusercontent.com/6333605b521a1e34fb21fe22/fa4812df-c8a7-46b3-8150-3257b03d5e1c)

I was able to add 
```
  .Toastify__toast-body {
    overflow: auto;
  }
```
to the base.css in order to get a horizontal scroll bar and the ability to delete the notification. All jupyter extensions with an initial commit have a base.css except for dps-server-jupyter-extension

However, there is a clause in the jupyterlab 3.6.x code that the message [will be truncated if longer than 140 characters](https://github.com/jupyterlab/jupyterlab/blob/c5ebd3af006fa4abd0fada9dd114dc28a90d01bc/packages/apputils/src/notification.ts#L254), and I am seeing that reflected in the notifications. Is that okay the messages will be limited to 140 characters?

I tried for a while to get a vertical scroll instead of a horizontal scroll, but I can only get a horizontal scroll despite following the instructions [here](https://www.w3schools.com/css/css_overflow.asp) for `overflow-y`. I think this might not be working because I am only limited to 140 characters so a vertical scroll isn't necessary

**Comment by gchang** [comment]
Ah, it's limited to the same character length as (old) Twitter. :) I think the 140 limit is fine.

**Comment by grallewellyn** [comment]
Done and deployed for:
- edsc jupyter extension
- dps jupyter extension 
- maap libs jupyter extension 
Done and still need to release new version, but releasing with another bug fix:
- maap help jupyter extension
- user workspace management jupyter extension
