### ISSUE TITLE
Implement new algorithm ui frontend jupyter extension

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/Community#686]
Figma: https://www.figma.com/file/7yf3qkld60PuLRer06Sahl/Algorithm-Registration?node-id=737%3A5819&t=fWfJVTZi0qoOV4gg-0

Lucid chart: https://lucid.app/lucidchart/7e98387d-dd84-4b4c-9c2b-598423601e22/edit?invitationId=inv_1a44f02a-0ceb-45c3-a50f-5ea2accb1a49&page=nVbkAi3R0I7r#

**Comment by marjo-luc** [comment]
Most of this is implemented. All that remains is a review of the UI/UX and repo verification on the user form.

**Comment by gchang** [comment]
Waiting for UX feedback @rtapella

**Comment by rtapella** [comment]
This is the algorithm-registration (not algorithm-list) UI right? 

I can set up usability testing for this sprint. 

I think we were also going to have some built-in help? Especially the container field.

**Comment by rtapella** [comment]
I could also test this along with the new DPS nuts-n-bolts tutorial:
https://docs.google.com/document/d/1jULblYS8CS3bdiyKIV6t_--urd8yDHQM8XJC9riHAeU/edit

**Comment by marjo-luc** [comment]
Yes, algo-registration ui. The v3.1.2 release will have some minor updates to the ui. If possible, we should review them internally before the release on 11/1.

**Comment by rtapella** [comment]
I think we should close this (dev) ticket and keep the usability-test open til that's done. I was able to do some testing via the DPS Tutorial and superficially it seems okay, except for the input form running off the page to the right.

**Comment by rtapella** [comment]
@marjo-luc is this one okay to close?
