### ISSUE TITLE
Jobs UI: Remove old Jobs-related menu items

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/Community#695]
Now that we have the jobs UI, remove all the old job-submission and job-tracking menu items.

![Screenshot 2023-03-20 at 9.47.06 AM.png](https://images.zenhubusercontent.com/61dc908470b3029fc627fcbb/f2497ea9-7a8e-4412-9dc6-48ba3d2b8fb1)

**Comment by rtapella** [comment]
![Screenshot 2023-03-20 at 9.48.04 AM.png](https://images.zenhubusercontent.com/61dc908470b3029fc627fcbb/967a1739-2b61-4d3f-806c-a2831f205871)

**Comment by marjo-luc** [comment]
Done. These menu options are no longer available in ops and replaced with the new Jobs UI.
