### ISSUE TITLE
Request for `r5.4xlarge` queue/instance for FireNRT Algorithm

### ISSUE THREAD

**Issue by ranchodeluxe** [MAAP-Project/Community#706]
**Is your feature request related to a problem? Please describe.**

We have a FireNRT algorithm that runs six times a day in DPS. It's currently being optimized to run globally. It would help if we could also have more CPU to spin up and parallelize across more dask workers. 

**Describe the solution you'd like**

We'd like to have access to a `r5.4xlarge` queue/instance for FireNRT Algorithm to prototype running globally

**Describe alternatives you've considered**

Other instance types. But we're shooting for 12-14 dask workers

**Additional context**

None

**Comment by mccabete** [comment]
Hello @gchang , 

Could we get an idea of the timeline for this resource ticket? We are doing project planning and trying to get sense of how MAAP resources becoming available may / may not effect our timeline.

**Comment by mccabete** [comment]
Thank you for getting back to me! I will let EIS Fire folks know for our planning. We appreciate it!

**Comment by sujen1412** [comment]
Hi @mccabete , 

Do you have an algorithm that we could use to test the new resource group ? 
You can use the `maap-dps-worker-128gb` queue for submissions.

**Comment by mccabete** [comment]
Hey @sujen1412,

Thanks for the fast response! `eis_fire_archive_2012_ubuntu:conus_archive_dps_2012` would be a good algorithm for testing!

**Comment by mccabete** [comment]
I will also let people know that they can select the `maap-dps-worker-128gb`
