### ISSUE TITLE
Update Admin Email notifications for new OPS

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/Community#708]
The email notifications sent to Admins do not distinguish between the old and new OPS environments.

**Comment by anilnatha** [comment]
@bsatoriu I tried testing the email functionality on DIT by changing the status of my account to 'suspended', but the server is reporting a CORS issue now.

<img width="1749" alt="image" src="https://github.com/MAAP-Project/ZenHub/assets/931107/d80f0a90-d4e5-49af-86d9-6cd7e4afe3f3">

**Comment by bsatoriu** [comment]
@sujen1412 I traced this error to the Sister update merge: this change to maapapp.py removed the CORS support from the API: https://github.com/MAAP-Project/maap-api-nasa/commit/039a2fc8ccbfcdcb6ae6090f4e1c5b492ccacdcc#diff-498e7e9ce41fa36f7168c73b547b2bc169a94f4f20a1944c7fcb194b81ecd292

**Comment by sujen1412** [comment]
I can re-add those lines, do you want me to add them or have you already done that?

**Comment by bsatoriu** [comment]
@anilnatha this is ready for your PR approval to get the admin CORS error fixed: https://github.com/MAAP-Project/maap-api-nasa/pull/64

**Comment by anilnatha** [comment]
@bsatoriu PR approved

**Comment by oddes** [comment]
@anilnatha is ready for test?

**Comment by anilnatha** [comment]
@oddes This was deployed in May with a patch completed in June. It can be tested in UAT/OPS; however, it has been working as expected and we haven't heard of any issues with it. So feel free to verify on your end or close the issue as you see fit.

**Comment by oddes** [comment]
Great. Thanks. Looks good.
