### ISSUE TITLE
Revisit WPS endpoints for executing jobs via API w/authentication

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/Community#717]
## Authenticated DPS communication to the MAAP API

This feature enables secure authentication between DPS and the MAAP API. Authentication is achieved using a combination of the job submitter's username, a machine token shared between the DPS system and MAAP API, and an additional session_key field in the `api.maap-project.org/api/members/{username}` output accessible via the new DPS machine token.

### DPS User Impersonation Process

- Bundle an API machine token into algorithm package during registration as an environment variable
- After job submission, and before algorithm execution, the DPS wrapper requests a user proxy token from the MAAP API
  - DPS wrapper sends a request to **api.maap-project.org/api/members/{username}**
  - DPS wrapper includes the machine token in the request header.
  - Value of **{username}** is retrieved from the local **_job.txt** HySDS file. The username belongs to the user submitting the job.
- The MAAP_PGT env variable is set inside the job container
  - The output of the API endpoint includes the most recent user session token, or MAAP_PGT value, guaranteeing a valid session for DPS impersonation.
  - The MAAP_PGT env variable is used by the maap-py library to make secure API requests.
- Unset the DPS machine token environment variable prior to algorithm execution

### Secure DPS endpoints

Several DPS endpoints such as job submission and algorithm registration will no longer be publicly accessible after this update. Consequently, it will be necessary to set the `MAAP_PGT` environment variable to a valid token (obtainable from the ADE environment) if running the [maap-py library ](https://github.com/MAAP-Project/maap-py)from outside of the ADE environment.

**Comment by bsatoriu** [comment]
### Testing notes @oddes 

1. Ensure a new algorithm can be registered and executed that successfully generates output from a `maap-py` method requiring a valid MAAP_PGT token:
    - `maap.profile.account_info()`
    - `maap.registerAlgorithm()`
    - `maap.submitJob()`
    - `maap.deleteAlgorithm()`
3. In a new workspace, ensure that these same `maap-py` methods can be ran successfully after leaving the workspace open for longer than 30 minutes.
