### ISSUE TITLE
Return GitLab account info on status update

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/Community#724]
Currently, the `/api/members/username/status` endpoint only synchronizes GitLab account info for first-time status activations. We need to also synchronize GitLab account info for re-activations.

**Comment by oddes** [comment]
@bsatoriu is this ready to test? so I can test and close.

**Comment by bsatoriu** [comment]
@oddes yes this is ready in OPS to test. Testing notes:

1. Deactivate a test user in the WordPress MAAP Admin tab.
2. Ensure the deactivated user no longer has GitLab access (repo.maap-project.org)
3. Reactivate the same test user.
4. Verify user now as GitLab access.
