### ISSUE TITLE
Update all jupyter extensions to jupyterlab 4.0.0

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/Community#728]

**Comment by grallewellyn** [comment]
https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#jupyterlab-3-x-to-4-x

**Comment by gchang** [comment]
Might not be necessary now with 3.6.4

**Comment by grallewellyn** [comment]
Doesn't seem necessary anymore, PR submitted that should fix bug
