### ISSUE TITLE
Change to libmamba solver

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/Community#731]

**Comment by grallewellyn** [comment]
Getting `AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'` when trying to run all base images in the develop branch for the R and isce2 base images. This PR fixes it: https://github.com/MAAP-Project/maap-workspaces/pull/43, but not ideal to be using pip when we should be using conda

@sujen1412 Found another fix where we could possibly use libmamba solver, https://repo.dit.maap-project.org/root/maap-workspaces/-/jobs/5084 but it fails on the jupyter image because "we are not installing mamba anymore. So we will have to make a systematic change to all images to use libmamba solver as thats the preferred way going forward"

**Comment by gchang** [comment]
This ticket is to convert all of the workspaces to use libmamba.

**Comment by grallewellyn** [comment]
Working with @anilnatha on this to combine this ticket with extracting package installs in image dockerfiles to be in an environment.yml

Right now, I can get just switching to use libmamba solver to work for all images (if I change the package versions for vanilla) in the feature/libmamba-solver branch in maap-workspaces 
But Anil was having some trouble combining libmamba solver to work with the environment.yml -> potentially because of conda env update line

**Comment by grallewellyn** [comment]
@wildintellect Anil mentioned that you said in the meeting Monday users should use mamba to install their packages
We are actively working on this ticket to switch from using mamba to install packages, to instead be conda install with the libmamba solver
This means users should (once this ticket is complete) use conda install with the libmamba solver to install packages. Is that a problem?

**Comment by wildintellect** [comment]
@grallewellyn that is an acceptable solution. We should clearly document this, and how users can use the `classic` solver if they want. This also doesn't negate that current images have `mamba` installed, but will make it so users don't have to remember that.
```
conda install -n base conda-libmamba-solver
conda config --set solver libmamba
```

**Comment by grallewellyn** [comment]
Sounds good!

**Comment by grallewellyn** [comment]
PR merged, but moved back into in progress because still need to run `conda config --set solver libmamba` or `--solver=libmamba` in ade terminal when installing packages to get faster run time. I tried for 5 packages, 3 are the same time without explicitly setting the solver, but 2 are faster when explicitly setting solver

Adding `conda config --set solver libmamba` to jupyterlab3 docker didn't help this. Going to keep working on trying to find a way to make libmamba solver apply when installing packages without user having to do anything setting it

**Comment by anilnatha** [comment]
@grallewellyn 

Right now we have this in the base pangeo dockerfile:

```
RUN conda install -y -c conda-forge pyOpenSSL=23.2.0 && \
    conda install -y -n base conda-libmamba-solver && \
    conda config --set solver libmamba

RUN conda install -y --solver=libmamba -c conda-forge gdal=3.6.2 matplotlib=3.6.2 Cython=0.29.33 h5py=3.7.0 numba=0.56.4 \
    pygeos=0.14 pyproj=3.4.1 rasterio=1.3.4 scipy=1.10.0 \
    && find /opt/conda/ -follow -type f -name '*.a' -delete \
    && find /opt/conda/ -follow -type f -name '*.js.map' -delete \
    && /opt/conda/bin/conda clean -afy
```

Can we try the following?:

```
RUN source /opt/conda/bin/activate base && \
    conda install -y -c conda-forge pyOpenSSL=23.2.0 && \
    conda install -y -n base conda-libmamba-solver && \
    conda config --env --set solver libmamba && \
    conda install -y --solver=libmamba -c conda-forge gdal=3.6.2 matplotlib=3.6.2 Cython=0.29.33 h5py=3.7.0 numba=0.56.4 \
    pygeos=0.14 pyproj=3.4.1 rasterio=1.3.4 scipy=1.10.0 \
    && find /opt/conda/ -follow -type f -name '*.a' -delete \
    && find /opt/conda/ -follow -type f -name '*.js.map' -delete \
    && /opt/conda/bin/conda clean -afy
```

Some of these lines could be cleaned up, but let's see if this change helps.

**Comment by anilnatha** [comment]
@grallewellyn researched this a bit more, that `source` command is going to fail because this isn't run in a bash shell. give me a little time, I'll try to fix it.

**Comment by wildintellect** [comment]
Correct you can't activate a conda env in a docker build.

**Comment by grallewellyn** [comment]
I was actually doing that testing before in conda environments that weren't base
When I repeat the tests of timing packages in the base environment, I am seeing similar times for running `conda install -y --solver=libmamba -c conda-forge gdal` and `conda install -y -c conda-forge gdal` and a much longer time for running `conda install -y --solver=classic -c conda-forge gdal`. Same goes for the xarray package

Therefore, I am assuming that libmamba is being applied correctly in base. But what if users don't want to use base and want to create a custom conda environment? From @anilnatha it sounds like we just need to tell them in the documentation to explicitly set `conda config --set solver libmamba` each time for new conda environments? 

Also, to reiterate what I said before in slack:
`conda config --describe | grep solver` says “classic” but `cat .condarc` says “solver: libmamba”. `conda config --show-sources` prints
```
==> /projects/.condarc <==
solver: libmamba

==> cmd_line <==
debug: False
json: False
```
`conda config --get solver` gives libmamba

**Comment by wildintellect** [comment]
No the conda config is not per environment, it should impact the whole conda install. e.g. there is only ever one install of `conda` 
So no need to document anything for users beyond what we've already described.

**Comment by grallewellyn** [comment]
Moving this back to in progress because there are bugs with this

**Comment by grallewellyn** [comment]
This will be resolved in the features/update-workspace-dependencies branch because we upgraded to the base image to `FROM continuumio/miniconda3:23.10.0-1` which has conda 3.10 which has libmamba as the default solver https://conda.org/blog/2023-11-06-conda-23-10-0-release/
