### ISSUE TITLE
View of Jupyter notebook will "reset" periodically  to first code block in ade.maap-project.org

### ISSUE THREAD

**Issue by mccabete** [MAAP-Project/Community#735]
**Describe the bug**
Every so often my jupyter  notebook view will "reset". Specifically, I will be working in a code block in the middle of a notebook, and then the notebook will stall, and my cursor will appear in the first code block of the notebook. This is when I am typing in the code block, not when I am executing code. 

**To Reproduce**
I do not 100% know how to reproduce this problem because it is intermittent. It seems to happen on multi-block python notebooks when you are editing  one of the later code blocks. 

**Expected behavior**
I expect to keep interactively editing without my cursor moving to the first code block. 

**Screenshots**
(Note, In the screenshot it looks like my code is executing during this bug, but that's just because I took an Ill-timed screenshot.)

![image (2)](https://github.com/MAAP-Project/ZenHub/assets/21266199/b8a5fbb4-9888-4e4c-ab8d-32442b9db29f)

![image (3)](https://github.com/MAAP-Project/ZenHub/assets/21266199/2bd93eab-1947-4448-b5cf-12a915060ba4)

**Notes:**
 - Browser: Firefox
 - on ade.maap-project.org, but doesn't happen on ade.ops.maap-project.org

**Additional context**
See [this slack discussion](https://esa-nasa-maap.slack.com/archives/C01308ZHELF/p1687274999403049).

**Comment by pahbs** [comment]
This issue happens frequently and is very disruptive to work being done in notebooks.

**Comment by mccabete** [comment]
#744 looks like it is also referring to this issue. I would also like to echo @pahbs's comment. It's almost work-stopping.

**Comment by mccabete** [comment]
Hey @rtapella, 

This is in the new ADE, and it's a workspace that was made close to the launch. It is exactly the bug  you mentioned, it is moving the cursor around.

**Comment by grallewellyn** [comment]
We already have a fix for this bug (which is removing the collaboration feature for now since this is a jupyterlab bug)
We will release this fix out to the ops environment in the next 1.5 weeks
