### ISSUE TITLE
Package list for a robust Base Python workspace for spatial-geoscience applications on MAAP

### ISSUE THREAD

**Issue by nmt28** [MAAP-Project/Community#743]
**Is your feature request related to a problem? Please describe.**
MAAP is designed for spatial geoscience applications, but base python env are missing commonly used packages, requiring user installation on workspace startup. This is time consuming and potentially unstable as package dependancies etc change

**Describe the solution you'd like**
A UWG defined list of core base env packages

**Describe alternatives you've considered**
Installation of key packages manually

**Additional context**
Env should be python >=3.10.X

Routine packages would include those that support, for example:
https://docs.google.com/spreadsheets/d/18Orw1cZbqUdOPBy9hFwXm43Pb0MZL7n1KEJuWO9UuIY/edit#gid=0

- data frame filtering and manipulation,
- aws file access,
- geospatial file access,
- spatial analysis,
- statistical analysis, and
- map generation.
- We can keep and update a list of package requests here:

**Comment by nmt28** [comment]
My suggested packages (includes those that may be dependancies for other packages):

- pandas
- geopandas
- gdal
- rasterio
- earthengine-api
- matplotlib
- shapely
- numpy
- tqdm
- scipy
- scikit-learn
- ipyleaflet
- ipykernel
- hdf5
- boto3
-

**Comment by mccabete** [comment]
- xarray
- rioxarray
- s3fs
- geocube
- folium

**Comment by wildintellect** [comment]
@mccabete would you prefer the Pangeo based workspace https://github.com/MAAP-Project/Community/issues/729?

**Comment by pahbs** [comment]
- matplotlib basemap toolkit
- plotnine
- mizani
- rio-cogeo
- rio-tiler
- morecantile
- pystac-client
- pygeos
- rtree
- pycurl
- rasterstats
- pandarallel

**Comment by anilnatha** [comment]
@pahbs 

Is my assessment of where these packages should be added accurate? I want to ensure that packages that should only be a part of ADE (jupyter) environment aren't added to the base (DPS) images.

Add to base (DPS) image, will also be available in ADE:
* matplotlib basemap toolkit
* mizani
* morecantile
* pandarallel

Add to ADE (jupyterlab) Image only:
* plotnine

**Comment by wildintellect** [comment]
@anilnatha my take, anything that is not interactive graphics should be in the Base, which allows users to produce static (saved as file) graphs. Which mean all of these should be in the base image.

**Comment by pahbs** [comment]
@anilnatha i agree with @wildintellect

**Comment by grallewellyn** [comment]
@pahbs By `toolkit`, did you mean `prompt-toolkit` or maybe `prompt_toolkit`?

**Comment by wildintellect** [comment]
@grallewellyn looks like `prompt-toolkit` is the pypi name for `prompt_toolkit` 
https://github.com/lauraduncanson/icesat2_boreal/blob/72ccd99136282986943cac32107ecdc360f97153/notebooks/3.Gridded_product_development/environment.yml#L248
https://pypi.org/project/prompt-toolkit/

Reading about this, seems it's only relevant to the Jupyter(ADE) images? https://python-prompt-toolkit.readthedocs.io/en/master/

@sujen1412 @anilnatha and I have discussed a few times if there's a recommended library for making python CLI easier beyond what's included.

Actually I'm very confused now too:
`conda install -c https://conda.anaconda.org/conda-forge prompt_toolkit`

**Comment by grallewellyn** [comment]
@wildintellect If our conda list has both
```
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
```
is that okay?

**Comment by wildintellect** [comment]
@grallewellyn https://stackoverflow.com/a/61717003/237354

**Comment by grallewellyn** [comment]
Thanks! I am going to assume this is what @pahbs meant by `toolkit` unless I hear otherwise
