### ISSUE TITLE
Autosave not working for Jupyter notebook on ade.ops

### ISSUE THREAD

**Issue by mccabete** [MAAP-Project/Community#748]
**Describe the bug**
While working on a Jupyter notebook on ade.ops, my notebook reverted to a previous save twice. The checkpoint file matched where my notebook had reset to, suggesting that Autosave wasn't working, or that it wasn't updating the checkpoint file. The checkpoint files was updated by a manual save. 

**To Reproduce**
I don't know exactly how to reproduce the behavior. Possibly working on a jupyter notebook on the ade.ops without manually saving can reproduce it. It happened for a notebook save to a `/shared-buckets/` bucket, and one on the `/projects/` path. 

**Expected behavior**
I expected autosave to be regularly saving my notebook ~120 seconds. 

**Additional context**
See this [slack discussion](https://esa-nasa-maap.slack.com/archives/C01308ZHELF/p1688152734700149).

**Comment by grallewellyn** [comment]
I am seeing the same behavior. To the user it seems like autosave is "saving" their notebook (ie the gray dot next to the notebook name goes away)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBankzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d2e515a1fd6e27730be4e898367e51ef094c3dbd/Screenshot%202023-09-19%20at%202.21.09%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanUzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f1119ef0735caf57a3a6052a1575d424f1dc3550/Screenshot%202023-09-19%20at%202.20.52%20PM.png)

But in `/projects/` and `my-private-bucket` and `my-public-bucket`, the checkpoint isn't being updated unless it is with a manual save 

I am seeing the same behavior locally for jupyterlab 3.6.3 and 4.0.6 (newest version)

**Comment by grallewellyn** [comment]
From researching more, I do not see any way for jupyterlab to implement automatic checkpointing, only automatic saving. I can also not find a way for jupyterlab to display the last checkpoint time, but @gchang is going to look more into this
Automatic checkpointing is not enabled for jupyter notebook either 
For now I made a PR to maap documentation explaining the user must manually save to checkpoint

**Comment by grallewellyn** [comment]
George confirmed that there isn't a way to say the last checkpoint time, so the best we can do is add to documentation telling people to manually save to checkpoint
