### ISSUE TITLE
Memory extension ADE

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/Community#749]

**Comment by grallewellyn** [comment]
Memory extension for jupyter for the ADE

**Comment by gchang** [comment]
Look to see if there is a cleaner solution from within the pod, possibly calling special URLs in the same way that we get the machine name and machine id in `entrypoint.sh`

**Comment by gchang** [comment]
Look to see if there is a cleaner solution from within the pod, possibly calling special URLs in the same way that we get the machine name and machine id in `entrypoint.sh`

**Comment by grallewellyn** [comment]
Agreed memory warning threshold should be .2 in discussion today

**Comment by grallewellyn** [comment]
@gchang When you say "calling special URLs in the same way that we get the machine name and machine id in entrypoint.sh" 
Are you referring to this line in entrypoint.sh
`che_workspace_id = os.environ.get('CHE_WORKSPACE_ID')`
or maybe this line: `request_string = 'https://' + svc_host + ':' + svc_host_https_port + '/api/v1/namespaces/' + namespace +  '/endpoints/'`
