### ISSUE TITLE
Selecting a queued job in the jobs UI (ade.maap) crashes the Jobs UI

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/Community#752]
**Describe the bug**
Selecting a queued job in the jobs UI (ade.maap) crashes the Jobs UI

**To Reproduce**
1. open up ade.maap-project.org
2. open up the Jobs UI
3. submit a new job
4. while it's queued, go to the job list
5. click the queued job
6. jobs UI goes blank (even if you re-open the jobs UI)
7. reload the workspace & check again. The jobs UI is back.

Once the job has started, the page no longer seems to crash. Potentially related to a queued-job not having a status/detail yet?

**Expected behavior**
Expect not to crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 13.4.1
 - Browser : Chrome
 - Version 114.0.5735.198 (Official Build) (arm64)

**Comment by marjo-luc** [comment]
Confirmed in ops this was fixed some time back:

<img width="1702" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKy9TQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f437650930fe6c2bff44ea67e13dca9d180b6b37/Screenshot%202024-07-11%20at%2012.30.35%E2%80%AFPM.png" alt="Screenshot 2024-07-11 at 12.30.35 PM.png" />
