### ISSUE TITLE
Create workspace for HySDS UI

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/Community#754]
Will also need to think about how to expose this to the users

**Comment by rtapella** [comment]
To make this official we should consider authorization issues and officially making “groups” so that a team of collaborators can potentially help manage each others’ jobs.

**Comment by rtapella** [comment]
To make this official we should consider authorization issues and officially making “groups” so that a team of collaborators can potentially help manage each others’ jobs.

**Comment by bsatoriu** [comment]
Moving this to milestone 3.1.4
