### ISSUE TITLE
Upgrade GitLab to v16; change auth provider to OIDC

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/Community#756]
CAS 3 support has been removed from GitLab v16. Details: https://gitlab.com/gitlab-org/gitlab/-/issues/369127

Change the auth provider to OIDC to ensure continuation of regular GitLab upgrades.

**Comment by bsatoriu** [comment]
DIT GitLab has been upgraded to version 16.1.2. I changed the omniauth provider from `cas3` to `openid_connect` by modifying the gitlab.rb configuration and updating the CAS GitLab service file: https://github.com/MAAP-Project/maap-auth-cas/commit/fd4a0e779c1043ac0b223052f74ab904d50cf4db

As part of this change, I configured GitLab to auto-link users to their new OIDC account when logging in from CAS to prevent profile conflicts. 

Testing requirements:

Ensure that an existing user with an account created before 7/17/2023 can login successfully to repo.dit.maap-project.org and see the account profile in GitLab. In your "authentication log" tab, you should see entries for both "cas3" and "openid_connect". See attached screenshot for reference.
![Screen Shot 2023-07-17 at 10 30 24 AM](https://github.com/MAAP-Project/Community/assets/27687558/33a7b593-9e54-439e-a23a-16abdbeefbd4)

**Comment by oddes** [comment]
This looks good:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2NPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26d8ff715685488668ac15274c36552f991ffed2/Screenshot%202023-08-16%20at%2012.15.34%20PM.png)
