### ISSUE TITLE
slow DPS submission using maap.submitJob()

### ISSUE THREAD

**Issue by pahbs** [MAAP-Project/Community#762]
**Describe the bug**
In the new ADE, using a loop in a notebook, jobs are submitted to DPS. This process is much slower that it used to be in ADE Ops (~10x slower - each job takes ~3 mins to submit). This slow submission is at the moment the main bottleneck to fast processing, as my current large batch of thousands cannot submit fast enough to approach the limit of simultaneous processes set to 2000. I am seeing max simultaneous DPS jobs at around 330.

This was discussed with @sujen1412

**Comment by oddes** [comment]
works as expected.
