### ISSUE TITLE
[Data]: Fire Weather Index Data from Weather Stations

### ISSUE THREAD

**Issue by mccabete** [MAAP-Project/Community#767]
**Dataset Name**
Fire Weather Index Data from Weather Stations over the Western US

**Dataset Description**
 Daily and hourly station-based Fire Weather Index calculations over the Western US. The main source of station data is the NOAA NCEI Integrated Surface Database (ISD). 

**Requestor name/affiliation**
Tempest McCabe - Goddard Space Flight Center 618
Robert Field  (@robertdfield) - Goddard Institute for Space Studies

**Platform/Instrument/Method**
Weather stations

**URL or DOI to dataset description**
Full read_me at `s3://veda-data-store-staging/EIS/other/station-FWI/20000101.20221021.hrlyInterp/README.DailyHourlyFWI.txt`

**URL to download or access data**
Data: `"s3://veda-data-store-staging/EIS/other/station-FWI/20000101.20221021.hrlyInterp/FWI/*`Each weather station has a unique `.csv` file. 
Underlying Source data: https://www.ncei.noaa.gov/products/land-based-station/integrated-surface-database

**Data License**
The data is not openly available right now. It would ideally be accessible to collaborators for download and use, but not appear on any searches until it is vetted. 

**Intended science use case**
The data will be used to understand the relationship between weather and fire risk and fire behavior. It will likely be pulled into visualizations, analyses, and publications.  

## Optional

**Approximate size of data**
Unknown

**Additional information**
This data will be updated semi-regularly through time. There are also similar datasets that correspond to different interpolation assumptions and different networks of weather stations. We are not yet requesting those be added to the STAC, but may in the future.

**Comment by wildintellect** [comment]
@mccabete @robertdfield a few clarifying questions.

1. This is data produced by your group?
2. You want to make the files publicly accessible but not discoverable?
3. Would people you want to share the data with be eligible for MAAP ADE or VEDA Jupyterhub access?

**Comment by mccabete** [comment]
hey @wildintellect 
1. yes. @robertdfield  is calculating the FWI data based on the weather station data. 
2. Yes
3. Yes they would be eligible. If possible, it would be nice to not make them sign up for an account because it's been a barrier in the past. 
4. -- No we *do* want this dataset added to the STAC. There are other similar datasets that exist on MAAP what we aren't ready to add to the STAC. I was trying to warn folks in this ticket that they may see similar-looking file structures that aren't a part of this dataset. 

4a. I don't know if I know what the difference would be from our end, if any?

**Comment by wildintellect** [comment]
@mccabete (cc: @robertdfield)
The data is hosted in VEDA buckets, if it was in STAC - the VEDA STAC would make sense, but that's not being asked right now

I see a few options, all of which are actually under the VEDA Data Services team, not MAAP.
Will check with @freitagb @j08lue @ranchodeluxe which repo this ticket should be moved to.

## Possible Solutions
1. Users are given access to the [JupyterHub](https://nasa-impact.github.io/veda-docs/services/jupyterhub.html), the required account is a Github account. (would like feedback if this is still a barrier). MAAP accounts are also possible but that takes EDL accounts and more approvals.
2. Presigned urls - since it only looks a like a few files, these could be generated. You would need a new one every update, and there are expiration (max is 7 days)
3. Make the prefix (aka folder) on S3 under which these files are located Public. VEDA team will need to chime in if this is an acceptable method policy-wise.

**Comment by mccabete** [comment]
@wildintellect  one other consideration is that I know of at least two of the people who would be interested in this data are matlab users. Do any of the STAC api's provide access for matlab?

**Comment by wildintellect** [comment]
STAC is a search API (https endpoints, aka urls), it returns a json which will contain the link to the data file at an S3 or https path. Compatibility with something like Matlab is dependent on what file format you have saved the data in. In this case it's a CSV if I read your docs correctly. So it's up to the Matlab user to implement downloading or reading the CSV from the bucket.

Were you perhaps asking about the Features API service that VEDA also offers for the Fire Perimeter data https://firenrt.delta-backend.com ?

**Comment by mccabete** [comment]
@wildintellect I was not. I was more asking about the libraries built around the different STACs. Like I know there is a python library for searching, but I'm less certain if stuff is as user friendly in MATLAB.

**Comment by j08lue** [comment]
> I'm less certain if stuff is as user friendly in MATLAB

Yeah, there are probably no clients like pystac for MATLAB, but you can still use HTTP calls to the STAC (REST) API to find your items and then load the assets from S3, for example. Just less conveniently.

A limitation is that VEDA buckets are currently not public and we do not have MATLAB in an environment that has access to them. (I just started a discussion on opening the bucket with requester pays: https://github.com/NASA-IMPACT/veda-architecture/issues/300).


> Will check with @freitagb @j08lue @ranchodeluxe which repo this ticket should be moved to.

[veda-data](https://github.com/NASA-IMPACT/veda-data), please, @wildintellect - but I currently neither have sufficient permissions on this or the other repo to transfer the issue.

**Comment by wildintellect** [comment]
This work is being transferred to VEDA under https://github.com/NASA-IMPACT/veda-data/issues/18
