### ISSUE TITLE
[Data]:

### ISSUE THREAD

**Issue by pahbs** [MAAP-Project/Community#770]
**Dataset Name**
This request is for an existing suite of gridded boreal-wide data that is currently at the ORNL DAAC and available through CMR to be included in the MAAP STAC.

**Dataset Description**
Boreal Forest Stand Age c. 2020
Annual Boreal Tree Canopy Cover 1984-2020

**Requestor name/affiliation**
Paul Montesano (NASA GSFC)

**Platform/Instrument/Method**
Landsat TM/ETM/OLI

**URL or DOI to dataset description**
https://daac.ornl.gov/cgi-bin/dsviewer.pl?ds_id=2012

**URL to download or access data**
Here is the ORNL DAAC CMR endpoint to this dataset:
https://cmr.earthdata.nasa.gov/search/granules.json?echo_collection_id=C2539841646-ORNL_CLOUD

**Data License**
*Is the data openly available? Please list the license if you know it (e.g. CC-BY)*

**Intended science use case**
These data will be useful during the analysis stage the follows MAAP-based data processing of boreal forest aboveground biomass maps.

## Optional

**Approximate size of data**
*Please estimate of how many GB/TB/PB the data is.*

**Additional information**
*Any additional info you think is relevant, possibly including spatial or temporal subset if applicable.*

**Comment by wildintellect** [comment]
@pahbs It looks like this dataset is already available, on S3 in EarthData Cloud, and in COG format. You should able to access it in a similar manner to HLS and GEDI L4B.
- https://docs.maap-project.org/en/latest/science/GEDI/GEDI_L4B.html
- https://docs.maap-project.org/en/latest/science/HLS/HLSL30.html

Please give those a try, and feel free to ask additional questions on https://github.com/orgs/MAAP-Project/discussions/categories/data

There's nothing that requires action on the part of the Data Team so I'm going to close this ticket.
