### ISSUE TITLE
404 launching EDSC

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/Community#788]

**Comment by grallewellyn** [comment]
This is only happening in DIT and is because https://ade.dit.maap-project.org:30052/ is not working 
@bsatoriu @wildintellect Do you guys know why https://ade.dit.maap-project.org:30052/ isn't working again and why it keeps failing? 

The last thread we had a similar conversation on is: https://github.com/MAAP-Project/maap-ade-edscproxy/issues/1

**Comment by grallewellyn** [comment]
Link is working now, but I am not sure what changed. Maybe just needed to run `sudo service apache2 restart`

**Comment by oddes** [comment]
@grallewellyn I  have verified in all browsers it works fine. can we close it?

**Comment by grallewellyn** [comment]
Yes we can close
