### ISSUE TITLE
Copy submit job code with formatting when using Submit Job UI

### ISSUE THREAD

**Issue by sujen1412** [MAAP-Project/Community#791]
Using the UI to copy code to jupyter notebook, it pastes it as one long line. 
Can it be pasted with formatting ? Like a new line for every new argument.

**Comment by marjo-luc** [comment]
Updated format. This is a sample of what the command looks like when pasted directly into a notebook:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU9RIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--38f2123f4d03109339d4c6cfdc162ed49a815e0a/format_update.png)

**Comment by oddes** [comment]
Looks good.
