### ISSUE TITLE
Earthdata login doesn't work in earthdata search

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/Community#803]

**Comment by grallewellyn** [comment]
I am seeing the same behavior
Going directly to the site https://ade.maap-project.org:30052/search (which is what ops is calling for the IFrame) doesn’t give me an error when I do earthdata login but doesn’t log me in once I am directed back
I think the problem is that the IFrame can’t open anything outside its proxy url. None of the links at the bottom work and clicking the EarthData Access button that takes you to https://access.earthdata.nasa.gov/?_ga=2.98621273.65764599.1694473936-76257002.1694035727 at the bottom also gives the same access.earthdata.nasa.gov refused to connect error

**Comment by grallewellyn** [comment]
Not allowing earthdata login or other url redirects. I will be working on the proxy's css to remove this as an option 
Something in the css changed for EarthData so that is why it isn't removing earthdata login anymore and that is likely why edsc stopped working to get datasets because it isn't registering that the url changed anymore and making that print statement (so related to https://github.com/MAAP-Project/Community/issues/789)

**Comment by oddes** [comment]
Hi @grallewellyn is this available in UAT for test?

**Comment by grallewellyn** [comment]
No because https://ade.uat.maap-project.org:30052/ is down 
cc @bsatoriu Do you know how to get the UAT edsc proxy up? I can also see these changes in ops already so not sure it is entirely necessary to test this in uat

**Comment by oddes** [comment]
it works as expected. closing.
